version: "3.8"

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Backend (Node.js + Express + Prisma)
  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/todoapp
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  # Frontend (React)
  frontend:
    build: ./client
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "start"]

volumes:
  mysql_data:
